# Generated by Django 5.0.3 on 2024-03-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Portal_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_model',
            old_name='company_name',
            new_name='number_of_openings',
        ),
        migrations.AddField(
            model_name='job_model',
            name='skills',
            field=models.TextField(null=True),
        ),
    ]
