# Generated by Django 5.0.3 on 2024-03-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Portal_App', '0002_rename_company_name_job_model_number_of_openings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='job_model',
            name='categories',
            field=models.ManyToManyField(null=True, to='Job_Portal_App.job_category'),
        ),
    ]
