# Generated by Django 5.0.3 on 2024-03-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Portal_App', '0004_remove_job_model_categories_delete_job_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='post',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
