# Generated by Django 5.0.3 on 2024-03-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Portal_App', '0005_recruiterprofile_company_name_recruiterprofile_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='post',
        ),
        migrations.AddField(
            model_name='custom_user',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='post',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
